algoritmo "semnome"
var
   x, y:inteiro
   procedimento soma( p1, p2:inteiro)
   inicio
   p1 <- p1 + 2
   p2 <- p2 +6
   escreval ("VALOR P1: ",p1)
   escreval ("VALOR P2: ",p2)
   escreval ("SOMA P1 + P2: ",p1 +p2)
   escreval ("========================")
   escreval (" ")
   fimprocedimento
inicio
   x <- 3
   y<- 4
   soma(x,y)
   escreval ("VALOR X: ",x)
   escreval ("VALOR Y: ",y)
fimalgoritmo