Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2023
Var
// Seção de Declarações das variáveis 
numpri = real
numseg = real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia (nome)
escreva ("Olá "  + nome + " bem vindo!")
Fimalgoritmo